# Site settings
title: Scott Radcliff
email: scott@scottradcliff.com
meta_description: "Personal website and blog of Scott Radcliff, Software Developer specializing in Ruby and Ruby on Rails."
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottradcliff.com" # the base hostname & protocol for your site
twitter_username: scottradcliff
github_username:  scottradcliff

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
gems: ['jekyll-paginate']
paginate: 10
permalink: :title.html

defaults:
  -
    scope:
      path: "posts"
    values:
      layout: "post"
      title: "[Draft] A Sample Post"
